version: '3.9'
services:
  backend:
    build:
      context: .  
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@database:5433/QuestLog
    depends_on:
      - database
    volumes:
      - ./frontend/public:/usr/src/app/frontend/public 

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: QuestLog
    ports:
      - "5433:5433"
