version: '3.9'
services:
  
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: QuestLog
    ports:
      - "5432:5432"
