version: '3.9'
services:
  backend:
    build:
      context: .  
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/QuestLog
    depends_on:
      - database
    volumes:
      - ./frontend/public:/usr/src/app/frontend/public 

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: QuestLog
    ports:
      - "5432:5432"
